// This file is auto-generated by scan_classes.ps1
// Updated on 02/04/2026 15:40:46

const CLASS_IMAGES = {
    "amplifier": "Image/Classes/Amplifier.webp",
    "annihilator": "Image/Classes/Annihilator.webp",
    "attacker": "Image/Classes/Attacker.webp",
    "observer": "Image/Classes/Observer.webp",
    "support": "Image/Classes/Support.webp",
    "tank": "Image/Classes/Tank.webp",
    "uniframe": "Image/Classes/Uniframe.webp",
    "vanguard": "Image/Classes/Vanguard.webp"
};

