const CUB_IMAGES = {
    "beep-boop": "Image/CUB/Beep-Boop.webp",
    "billie": "Image/CUB/Billie.webp",
    "boreas": "Image/CUB/Boreas.webp",
    "bramble angler": "Image/CUB/Bramble Angler.webp",
    "cavaliere": "Image/CUB/Cavaliere.webp",
    "cetus": "Image/CUB/Cetus.webp",
    "corvus": "Image/CUB/Corvus.webp",
    "dawn chorus": "Image/CUB/Dawn Chorus.webp",
    "diamaton": "Image/CUB/Diamaton.webp",
    "dreamwing": "Image/CUB/Dreamwing.webp",
    "fei lin": "Image/CUB/Fei Lin.webp",
    "frost oath": "Image/CUB/Frost Oath.webp",
    "guardrake": "Image/CUB/Guardrake.webp",
    "hades fangs": "Image/CUB/Hades Fangs.webp",
    "huiyu": "Image/CUB/Huiyu.webp",
    "jet jaeger": "Image/CUB/Jet Jaeger.webp",
    "levvi": "Image/CUB/Levvi.webp",
    "mirageblades": "Image/CUB/MirageBlades.webp",
    "motorbolt": "Image/CUB/Motorbolt.webp",
    "nitor": "Image/CUB/Nitor.webp",
    "noctiluca": "Image/CUB/Noctiluca.webp",
    "punchy": "Image/CUB/Punchy.webp",
    "rainbow": "Image/CUB/Rainbow.webp",
    "scaled rampart": "Image/CUB/Scaled Rampart.webp",
    "shadow wing": "Image/CUB/Shadow Wing.webp",
    "snow waltz": "Image/CUB/Snow Waltz.webp",
    "snowveil": "Image/CUB/Snowveil.webp",
    "toniris": "Image/CUB/Toniris.webp",
    "wrathfang": "Image/CUB/Wrathfang.webp"
};
