// This file is auto-generated by scan_elements.ps1
// Updated on 02/04/2026 15:40:51

const ELEMENT_IMAGES = {
    "burn": "Image/Elements/BURN.webp",
    "dark": "Image/Elements/DARK.webp",
    "fire": "Image/Elements/FIRE.webp",
    "freez": "Image/Elements/FREEZ.webp",
    "general": "Image/Elements/GENERAL.webp",
    "ice": "Image/Elements/ICE.webp",
    "light": "Image/Elements/LIGHT.webp",
    "nihl": "Image/Elements/NIHL.webp",
    "phys": "Image/Elements/PHYS.webp",
    "plasma": "Image/Elements/PLASMA.webp",
    "slash": "Image/Elements/SLASH.webp",
    "thunder": "Image/Elements/THUNDER.webp",
    "umbra": "Image/Elements/UMBRA.webp"
};
