const WEAPON_IMAGES = {
    "akasha keyblade": "Image/Weapons/Akasha Keyblade.webp",
    "alpha omega": "Image/Weapons/Alpha Omega.webp",
    "apollo": "Image/Weapons/Apollo.webp",
    "astraea": "Image/Weapons/Astraea.webp",
    "aurora": "Image/Weapons/Aurora.webp",
    "baji": "Image/Weapons/Baji.webp",
    "benediction": "Image/Weapons/Benediction.webp",
    "berserk fusion": "Image/Weapons/Berserk Fusion.webp",
    "big kamui": "Image/Weapons/Big Kamui.webp",
    "cestus": "Image/Weapons/Cestus.webp",
    "crimson howl": "Image/Weapons/Crimson Howl.webp",
    "cruel oath mod": "Image/Weapons/Cruel Oath Mod.webp",
    "dark falcon": "Image/Weapons/Dark Falcon.webp",
    "darkness": "Image/Weapons/Darkness.webp",
    "deathless flame": "Image/Weapons/Deathless Flame.webp",
    "devil sword dante": "Image/Weapons/Devil Sword Dante.webp",
    "dragon wind": "Image/Weapons/Dragon Wind.webp",
    "dream roamer": "Image/Weapons/Dream Roamer.webp",
    "durendal": "Image/Weapons/Durendal.webp",
    "empyrean wrath": "Image/Weapons/Empyrean Wrath.webp",
    "final arbiter": "Image/Weapons/Final Arbiter.webp",
    "flamewing of dawn": "Image/Weapons/Flamewing of Dawn.webp",
    "fudo myoo": "Image/Weapons/Fudo Myoo.webp",
    "fusion dragon": "Image/Weapons/Fusion Dragon.webp",
    "galatea": "Image/Weapons/Galatea.webp",
    "gungnir": "Image/Weapons/Gungnir.webp",
    "hackerstune": "Image/Weapons/HackersTune.webp",
    "hecate": "Image/Weapons/Hecate.webp",
    "hestia": "Image/Weapons/Hestia.webp",
    "hydro heat": "Image/Weapons/Hydro Heat.webp",
    "illuminare": "Image/Weapons/Illuminare.webp",
    "implosion": "Image/Weapons/Implosion.webp",
    "infinity": "Image/Weapons/Infinity.webp",
    "inverse chimera": "Image/Weapons/Inverse Chimera.webp",
    "inverse shadow": "Image/Weapons/Inverse Shadow.webp",
    "key of tempus gate stokes": "Image/Weapons/Key of Tempus Gate Stokes.webp",
    "lotus berserker": "Image/Weapons/Lotus Berserker.webp",
    "managarm": "Image/Weapons/Managarm.webp",
    "metis": "Image/Weapons/Metis.webp",
    "neon wayfarer": "Image/Weapons/Neon Wayfarer.webp",
    "nightblaze": "Image/Weapons/Nightblaze.webp",
    "orpheus lullaby": "Image/Weapons/Orpheus Lullaby.webp",
    "osseous guillotine": "Image/Weapons/Osseous Guillotine.webp",
    "ozma": "Image/Weapons/Ozma.webp",
    "peacemaker": "Image/Weapons/Peacemaker.webp",
    "perpetuity": "Image/Weapons/Perpetuity.webp",
    "phoenix": "Image/Weapons/Phoenix.webp",
    "prometheus": "Image/Weapons/Prometheus.webp",
    "purple peony": "Image/Weapons/Purple Peony.webp",
    "qinghe": "Image/Weapons/Qinghe.webp",
    "ramiel": "Image/Weapons/Ramiel.webp",
    "reconstruction of law": "Image/Weapons/Reconstruction of Law.webp",
    "renewed dawn": "Image/Weapons/Renewed Dawn.webp",
    "ripplesofthe aloft sea": "Image/Weapons/Ripplesofthe Aloft Sea.webp",
    "sakura": "Image/Weapons/Sakura.webp",
    "sarastro": "Image/Weapons/Sarastro.webp",
    "sariel": "Image/Weapons/Sariel.webp",
    "scale": "Image/Weapons/Scale.webp",
    "scion": "Image/Weapons/Scion.webp",
    "snore": "Image/Weapons/Snore.webp",
    "sorrow of fata morgana": "Image/Weapons/Sorrow of Fata Morgana.webp",
    "soul ripper": "Image/Weapons/Soul Ripper.webp",
    "soundofsilence": "Image/Weapons/SoundofSilence.webp",
    "stelmo": "Image/Weapons/StElmo.webp",
    "starvoyager": "Image/Weapons/StarVoyager.webp",
    "starlightglare": "Image/Weapons/StarlightGlare.webp",
    "thanatos": "Image/Weapons/Thanatos.webp",
    "tonitrus": "Image/Weapons/Tonitrus.webp",
    "type-4o lance": "Image/Weapons/Type-4O Lance.webp",
    "typezero": "Image/Weapons/TypeZero.webp",
    "virtuous contract": "Image/Weapons/Virtuous Contract.webp",
    "waldmeister": "Image/Weapons/Waldmeister.webp",
    "wolffang": "Image/Weapons/WolfFang.webp",
    "yamato": "Image/Weapons/Yamato.webp",
    "zeroscale": "Image/Weapons/ZeroScale.webp",
    "rock cannon": "Image/Weapons/★Rock Cannon.webp"
};
