
# Valid class names to look for (lowercase keys mostly)
# We will just scan all PNGs in Image/Classes
$targetDir = "Image/Classes"
$outputFile = "js/class_images.js"

# Ensure output directory exists (it should)
$jsDir = "js"
if (!(Test-Path $jsDir)) {
    New-Item -ItemType Directory -Path $jsDir | Out-Null
}

$files = Get-ChildItem -Path $targetDir -Filter "*.png"

$timestamp = Get-Date -Format "MM/dd/yyyy HH:mm:ss"
$content = @"
// This file is auto-generated by scan_classes.ps1
// Updated on $timestamp

const CLASS_IMAGES = {
"@

$lines = @()

foreach ($file in $files) {
    # Key is filename without extension, lowercased
    $key = $file.BaseName.ToLower()
    # Path is relative to HTML file: Image/Classes/filename.png
    $path = "Image/Classes/$($file.Name)"
    
    $lines += "    `"$key`": `"$path`""
}

$content += $lines -join ",`n"
$content += "`n};`n"

Set-Content -Path $outputFile -Value $content -Encoding UTF8
Write-Host "Generated $outputFile with $($files.Count) entries."
