
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$imagesDir = Join-Path $scriptDir "Image\Memories"
$outputFile = Join-Path $scriptDir "js\memory_data.js"

Write-Host "Scanning directory: $imagesDir" -ForegroundColor Cyan

if (-not (Test-Path $imagesDir)) {
    Write-Host "Error: Directory not found!" -ForegroundColor Red
    exit
}

# Find unique memory names based on pattern Memory-[Name]-Icon-[1-3].png
$files = Get-ChildItem -Path $imagesDir -Filter "*.png"
$memoryNames = @()

foreach ($file in $files) {
    if ($file.Name -match "Memory-(.+)-Icon-\d\.png") {
        $name = $matches[1]
        if ($name -notin $memoryNames) {
            $memoryNames += $name
        }
    }
}

$memoryNames = $memoryNames | Sort-Object

$count = $memoryNames.Count
Write-Host "Found $count unique memory sets." -ForegroundColor Green

# Generate JS content
$jsContent = @"
// This file is auto-generated by scan_memories.ps1
// Updated on $(Get-Date)

const MEMORY_NAMES = [
"@

foreach ($name in $memoryNames) {
    $jsContent += "`n    `"$name`","
}

# Remove trailing comma if needed (JS allows it but cleaner without usually)
$jsContent = $jsContent.TrimEnd(",") 

$jsContent += @"

];
"@

Set-Content -Path $outputFile -Value $jsContent -Encoding UTF8

Write-Host "Successfully updated $outputFile" -ForegroundColor Cyan
Write-Host "Refresh the page to see changes." -ForegroundColor Yellow
Start-Sleep -Seconds 3
