$sourceDir = "Image/Elements"
$outputFile = "js/element_images.js"

# Ensure output directory exists
$jsDir = "js"
if (-not (Test-Path $jsDir)) {
    New-Item -ItemType Directory -Path $jsDir | Out-Null
}

# Ensure source directory exists (create if missing to avoid errors)
if (-not (Test-Path $sourceDir)) {
    New-Item -ItemType Directory -Path $sourceDir -Force | Out-Null
    Write-Host "Created missing directory: $sourceDir"
}

$images = @()
Get-ChildItem -Path $sourceDir -Include *.png, *.jpg, *.jpeg, *.webp -Recurse | ForEach-Object {
    $relativePath = "Image/Elements/" + $_.Name
    $key = $_.BaseName.ToLower()
    # Escape backslashes for JS
    # $relativePath = $relativePath -replace "\\", "/"
    
    $images += "`"$key`": `"$relativePath`""
}

$jsContent = @"
// This file is auto-generated by scan_elements.ps1
// Updated on $(Get-Date -Format "MM/dd/yyyy HH:mm:ss")

const ELEMENT_IMAGES = {
    $($images -join ",`n    ")
};
"@

$jsContent | Set-Content -Path $outputFile -Encoding UTF8
Write-Host "Scanned $($images.Count) element images. Saved to $outputFile"
