
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$imagesDir = Join-Path $scriptDir "Image\Characters"
$outputFile = Join-Path $scriptDir "js\character_images.js"

Write-Host "Scanning directory: $imagesDir" -ForegroundColor Cyan

if (-not (Test-Path $imagesDir)) {
    Write-Host "Error: Directory not found!" -ForegroundColor Red
    exit
}

$files = Get-ChildItem -Path $imagesDir -Filter "*.png"
$charImages = @()

foreach ($file in $files) {
    if ($file.Name -match "Coating-(.+)-.+\.png") {
        $frame = $matches[1]
        
        $charImages += [PSCustomObject]@{
            Frame = $frame
            File  = "Image/Characters/" + $file.Name
        }
    }
}

$count = $charImages.Count
Write-Host "Found $count character images." -ForegroundColor Green

$jsContent = @"
// This file is auto-generated by scan_characters.ps1
// Updated on $(Get-Date)

const CHARACTER_IMAGES = [
"@

foreach ($img in $charImages) {
    $jsContent += "`n    { frame: `"$($img.Frame)`", file: `"$($img.File)`" },"
}

$jsContent = $jsContent.TrimEnd(",") 

$jsContent += @"

];
"@

Set-Content -Path $outputFile -Value $jsContent -Encoding UTF8

Write-Host "Successfully updated $outputFile" -ForegroundColor Cyan
Write-Host "Refresh the page to see changes." -ForegroundColor Yellow
Start-Sleep -Seconds 3
